### ISSUE TITLE
使用template报错无法找到.github/feishu_msg_tmpl/example.json

### ISSUE THREAD

**Issue by JLBQ** [xiachufang/actions-feishu#10]
首先大赞下厨房分享的这个工具！
如果可以得到帮助的真的非常感谢！
正常的post功能我可以完整使用
但是按照例子使用template type时，action会报错 无法找到.github/feishu_msg_tmpl/example.json想请教一下是什么原因，谢谢！
![Capture1](https://user-images.githubusercontent.com/106563792/210962557-0e304655-093d-44bf-a2bc-420449964005.PNG)

**Comment by x1ah** [comment]
@JLBQ `.github/feishu_msg_tmpl/example.json` 这是个模板文件的路径，如果你要用这个消息模板，需要把这个仓库的 [这个文件](https://github.com/xiachufang/actions-feishu/blob/main/.github/feishu_msg_tmpl/example.json) 拷到你的代码仓库里去，再把 `INPUT_MSG_TEMPLATE_PATH` 的值改成你那个文件路径。

**Comment by JLBQ** [comment]
原来如此，成功了，谢谢！
